# Generated by Django 5.0.1 on 2024-01-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseparticipant',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
