# Generated by Django 5.0.1 on 2024-01-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenseparticipant_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12, null=True),
        ),
    ]
