# Generated by Django 5.0.1 on 2024-01-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_userprofile_net_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseparticipant',
            name='utr_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
