# Generated by Django 4.2.9 on 2024-01-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expenseparticipant_utr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseparticipant',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
    ]
